create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.applications
  add column if not exists name text,
  add column if not exists specialization text;

alter table public.applications enable row level security;

grant insert on table public.applications to anon;
grant usage, select on sequence public.applications_id_seq to anon;

drop policy if exists "Allow public application submissions" on public.applications;

create policy "Allow public application submissions"
on public.applications
for insert
to anon
with check (
  char_length(trim(name)) > 0
  and char_length(trim(specialization)) > 0
);
